### ISSUE TITLE
Not at the state of the art of flutter plugins

### ISSUE THREAD

**Issue by Tiska** [adobe/flutter_acpcore#10]
This plugin is not at the state of the art for flutter plugins : https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

As a result, it's not easy to integrate to recent flutter apps, writen in kotlin for example for the Android part. All the init logic and lifecycle activity bindings should be done in the plugin not in the android parent project activity. Plus you could use a property in the manifest and for ios in .plist to register app id. 

Do you plan to upgrade this plugin to the latest Flutter api ?

**Comment by nporter-adbe** [comment]
@Tiska It is required for our SDK to be initialized and registered in native code, same with Lifecycle metrics. This ensures that you can get the most accurate Lifecycle metrics. We have purposely made this design decision when creating this wrapper. 

Regarding supplying the app id via the manifest or property list in iOS, this isn't something we support in our native SDKs, and don't plan to add support for in the future.
