### ISSUE TITLE
Getting error Could not determine artifacts for com.adobe.marketing.mobile:core:1.5.7

### ISSUE THREAD

**Issue by Aashique** [adobe/flutter_acpcore#22]
When running the app getting the following error.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not determine artifacts for com.adobe.marketing.mobile:core:1.5.7: Skipped due to earlier error

**Comment by cdhoffmann** [comment]
Can you share your pubspec.yml file please? @Aashique

**Comment by Aashique** [comment]
version: 5.0.11+1100071

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  google_maps_flutter: ^2.1.1
  map_launcher: ^2.1.2
  url_launcher: ^6.1.3
  badges: ^2.0.2
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  geolocator: ^8.0.3
  flutter_google_places: ^0.3.0
  flutter_svg: ^1.0.3
  webview_flutter: ^3.0.0
  network_info_plus: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  equatable: ^2.0.3
  html: ^0.15.0
  google_place: ^0.4.7
  flutter_native_splash: 1.3.2
  async_task: ^1.0.17
  google_geocoding: ^0.2.0
  flutter_secure_storage: ^5.0.2
  flutter_appauth : 2.4.1
  dropdown_button2: ^1.2.2
  connectivity_plus: ^2.2.1
  pkce: ^1.1.0
  nonce: ^1.2.0
#  flutter_jailbreak_detection: ^1.8.0
  timezone: ^0.8.0
  flutter_overlay_loader: ^2.0.0
  flutter_acpanalytics: ^2.0.1
  flutter_acpcore: ^2.0.1
  screen_protector: ^1.1.1
  package_info_plus: ^1.4.2

**Comment by Aashique** [comment]
The issue is now resolved. able to run the app without any issues. yesterday JCaneter was down. that may be the issue.
hence closing the thread.
