### ISSUE TITLE
Support for Mobile Core SDK 2.x

### ISSUE THREAD

**Issue by TAC911** [adobe/flutter_acpcore#24]
We would like to know if there is a plan or even a date when support Mobile Core SDK 2.x will be available.

**Comment by ahmyr** [comment]
@TAC911, these are coming very soon!

**Comment by TAC911** [comment]
Hi @ahmyr . Thank your for the reply. What is the planned publishing date?

**Comment by ahmyr** [comment]
@TAC911, these are now available :) 
https://developer.adobe.com/client-sdks/documentation/current-sdk-versions/#flutter
