### ISSUE TITLE
Is there a any way to stop MobilCore?

### ISSUE THREAD

**Issue by kerimknd** [adobe/flutter_acpcore#25]
After starting MobilCore, I need to stop it again. Is there any method for this?

**Comment by cdhoffmann** [comment]
Hey, there is no method for stopping it once its started.

**Comment by TAC911** [comment]
@cdhoffmann We are using Adobe Analytics in connection with a consent management solution (OneTrust). User can agree to share analytics data or revoke her agreement. Revoking agreement can be done in user preferences. Once user revokes her agreement MobileCore keeps collecting data until app is killed and re-started. What is the approach of Adobe to stop collecting data when users revoke their agreement in the app during runtime?

**Comment by cdhoffmann** [comment]
@TAC911 You use the setPrivacyStatus API and set the privacy status to optOut. Here is some reference docs for how to do this in our Flutter wrapper: https://github.com/adobe/flutter_acpcore#setting-the-privacy-status. This will stop any hits from going to Analytics, and will clear any queued hits.
