### ISSUE TITLE
Starting and stopping analytics data collection with OneTrust configuration

### ISSUE THREAD

**Issue by TAC911** [adobe/flutter_acpcore#26]
We are using Adobe Analytics in connection with a consent management solution (OneTrust). User can agree to share analytics data or revoke her agreement. Revoking agreement can be done in user preferences. Once user revokes her agreement MobileCore keeps collecting data until app is killed and re-started. 

What is the approach of Adobe to stop collecting data immediately when user revoke her consent in the app (during runtime)?

**Comment by cdhoffmann** [comment]
@TAC911 You use the setPrivacyStatus API and set the privacy status to optOut. Here is some reference docs for how to do this in our Flutter wrapper: https://github.com/adobe/flutter_acpcore#setting-the-privacy-status. This will stop any hits from going to Analytics, and will clear any queued hits.
